#!/bin/bash

sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.1_lmda_0.05.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.3_lmda_0.01.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.1_lmda_0.01.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.8_lmda_0.1.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.5_lmda_0.01.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.5_lmda_0.1.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.3_lmda_0.002.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.8_lmda_0.2.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.8_lmda_0.01.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.3_lmda_0.05.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.1_lmda_0.0005.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.8_lmda_0.002.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.8_lmda_0.05.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.8_lmda_0.0005.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.5_lmda_0.001.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.1_lmda_0.001.sh
sbatch ./bash/cc/quickdraw/quickdraw_bash_p_0.3_lmda_0.001.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.1_lmda_0.1.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.5_lmda_0.002.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.002.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.2.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.8_lmda_0.05.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.5_lmda_0.001.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.1_lmda_0.01.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.5_lmda_0.1.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.1.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.01.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.1_lmda_0.05.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.1_lmda_0.001.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.05.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.1_lmda_0.002.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.8_lmda_0.2.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.5_lmda_0.0005.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.1_lmda_0.2.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.0005.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.3_lmda_0.001.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.5_lmda_0.01.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.8_lmda_0.002.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.8_lmda_0.001.sh
sbatch ./bash/cc/infograph/infograph_bash_p_0.8_lmda_0.1.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.01.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.2.sh
sbatch ./bash/cc/real/real_bash_p_0.3_lmda_0.01.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.001.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.1.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.2.sh
sbatch ./bash/cc/real/real_bash_p_0.3_lmda_0.001.sh
sbatch ./bash/cc/real/real_bash_p_0.3_lmda_0.0005.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.002.sh
sbatch ./bash/cc/real/real_bash_p_0.3_lmda_0.002.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.2.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.0005.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.0005.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.001.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.0005.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.05.sh
sbatch ./bash/cc/real/real_bash_p_0.3_lmda_0.1.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.05.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.001.sh
sbatch ./bash/cc/real/real_bash_p_0.5_lmda_0.01.sh
sbatch ./bash/cc/real/real_bash_p_0.3_lmda_0.2.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.01.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.1.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.1.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.002.sh
sbatch ./bash/cc/real/real_bash_p_0.1_lmda_0.002.sh
sbatch ./bash/cc/real/real_bash_p_0.8_lmda_0.05.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.5_lmda_0.2.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.5_lmda_0.05.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.3_lmda_0.001.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.1_lmda_0.1.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.5_lmda_0.001.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.1_lmda_0.05.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.3_lmda_0.1.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.1_lmda_0.001.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.1_lmda_0.002.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.5_lmda_0.1.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.3_lmda_0.2.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.8_lmda_0.001.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.8_lmda_0.01.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.1_lmda_0.2.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.8_lmda_0.002.sh
sbatch ./bash/cc/sketch/sketch_bash_p_0.3_lmda_0.01.sh
sbatch ./bash/cc/painting/painting_bash_p_0.8_lmda_0.2.sh
sbatch ./bash/cc/painting/painting_bash_p_0.5_lmda_0.002.sh
sbatch ./bash/cc/painting/painting_bash_p_0.3_lmda_0.2.sh
sbatch ./bash/cc/painting/painting_bash_p_0.3_lmda_0.05.sh
sbatch ./bash/cc/painting/painting_bash_p_0.8_lmda_0.1.sh
sbatch ./bash/cc/painting/painting_bash_p_0.8_lmda_0.01.sh
sbatch ./bash/cc/painting/painting_bash_p_0.8_lmda_0.05.sh
sbatch ./bash/cc/painting/painting_bash_p_0.5_lmda_0.1.sh
sbatch ./bash/cc/painting/painting_bash_p_0.5_lmda_0.05.sh
sbatch ./bash/cc/painting/painting_bash_p_0.8_lmda_0.001.sh
sbatch ./bash/cc/painting/painting_bash_p_0.5_lmda_0.01.sh
sbatch ./bash/cc/painting/painting_bash_p_0.5_lmda_0.2.sh
sbatch ./bash/cc/painting/painting_bash_p_0.8_lmda_0.0005.sh
